"""create_initial_schema_from_models

Revision ID: 31868b6b664b
Revises:
Create Date: 2025-06-03 22:33:26.040877

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31868b6b664b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clients_display_name"), "clients", ["display_name"], unique=False
    )
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("output_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "input_text_compact", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "validation_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PARSED",
                "ROLES_VERIFIED",
                "INPUT_SYNTHESIZED",
                "INPUT_CURATED",
                "VALIDATED",
                "EXPORTED",
                name="rolestatus",
            ),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_client_id"), "roles", ["client_id"], unique=False)
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "source_documents",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_final_resume", sa.Boolean(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("checksum", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_documents_client_id"),
        "source_documents",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_documents_id"), "source_documents", ["id"], unique=False
    )
    op.create_table(
        "evidence_snippets",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("role_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("snippet_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_snippets_id"), "evidence_snippets", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_snippets_role_id"),
        "evidence_snippets",
        ["role_id"],
        unique=False,
    )
    op.create_table(
        "validation_notes",
        sa.Column("role_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "notes_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id"),
    )
    op.create_index(
        op.f("ix_validation_notes_role_id"),
        "validation_notes",
        ["role_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_validation_notes_role_id"), table_name="validation_notes")
    op.drop_table("validation_notes")
    op.drop_index(op.f("ix_evidence_snippets_role_id"), table_name="evidence_snippets")
    op.drop_index(op.f("ix_evidence_snippets_id"), table_name="evidence_snippets")
    op.drop_table("evidence_snippets")
    op.drop_index(op.f("ix_source_documents_id"), table_name="source_documents")
    op.drop_index(op.f("ix_source_documents_client_id"), table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_client_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_display_name"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
