"""Initial schema from 02_DATA-MODEL (manual)

Revision ID: 3901b04c2d11
Revises:
Create Date: 2025-06-03 20:25:26.730093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# It's good practice to import SQLModel types if you use them directly in migrations,
# but for raw SQL, it's not strictly necessary.
# import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3901b04c2d11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Manually copied and adjusted DDL from database_schema.sql

    # Enums
    op.execute("""
    CREATE TYPE job_status AS ENUM (
        'PENDING',
        'RUNNING',
        'COMPLETED',
        'FAILED',
        'CANCELLED'
    );
    """)
    op.execute("""
    CREATE TYPE source_node_status AS ENUM (
        'PENDING',
        'PROCESSING',
        'COMPLETED',
        'ERROR_PARSING',
        'ERROR_CHUNKING',
        'ERROR_PII_DETECTION',
        'SKIPPED'
    );
    """)
    op.execute("""
    CREATE TYPE content_item_status AS ENUM (
        'RAW',
        'PII_DETECTED',
        'REDACTED',
        'VALIDATED',
        'EXPORTED'
    );
    """)
    op.execute("""
    CREATE TYPE pii_type AS ENUM (
        'PERSON',
        'PHONE_NUMBER',
        'EMAIL_ADDRESS',
        'LOCATION',
        'DATE_TIME',
        'US_SSN',
        'CREDIT_CARD',
        'ORGANIZATION',
        'CUSTOM_REGEX_1'
    );
    """)
    op.execute("""
    CREATE TYPE data_source_type AS ENUM (
        'LOCAL_ZIP',
        'LOCAL_FOLDER',
        'NOTION',
        'GOOGLE_DRIVE',
        'CONFLUENCE'
    );
    """)

    # Tables
    op.execute("""
    CREATE TABLE data_sources (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL UNIQUE,
        type data_source_type NOT NULL,
        config JSONB NOT NULL,
        description TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    """)
    op.execute("CREATE INDEX idx_data_sources_type ON data_sources(type);")

    op.execute("""
    CREATE TABLE pipeline_runs (
        id SERIAL PRIMARY KEY,
        data_source_id INTEGER REFERENCES data_sources(id) NULL,
        source_identifier TEXT NOT NULL,
        pipeline_config_name VARCHAR(255),
        status job_status NOT NULL DEFAULT 'PENDING',
        start_time TIMESTAMP WITH TIME ZONE,
        end_time TIMESTAMP WITH TIME ZONE,
        report JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    """)
    op.execute("CREATE INDEX idx_pipeline_runs_status ON pipeline_runs(status);")
    op.execute("CREATE INDEX idx_pipeline_runs_start_time ON pipeline_runs(start_time DESC);")

    op.execute("""
    CREATE TABLE source_nodes (
        id SERIAL PRIMARY KEY,
        pipeline_run_id INTEGER NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
        source_uri VARCHAR(2048) NOT NULL,
        internal_path VARCHAR(2048) NULL,
        file_type_detected VARCHAR(50),
        file_type_provided VARCHAR(50),
        content_hash VARCHAR(64),
        metadata JSONB,
        status source_node_status NOT NULL DEFAULT 'PENDING',
        processing_log TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (pipeline_run_id, source_uri)
    );
    """)
    op.execute("CREATE INDEX idx_source_nodes_status ON source_nodes(status);")
    op.execute("CREATE INDEX idx_source_nodes_pipeline_run_id ON source_nodes(pipeline_run_id);")
    op.execute("CREATE INDEX idx_source_nodes_file_type_detected ON source_nodes(file_type_detected);")
    op.execute("CREATE INDEX idx_source_nodes_content_hash ON source_nodes(content_hash);")

    op.execute("""
    CREATE TABLE raw_content_store (
        id SERIAL PRIMARY KEY,
        source_node_id INTEGER NOT NULL REFERENCES source_nodes(id) ON DELETE CASCADE UNIQUE,
        extracted_text TEXT,
        extraction_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        parser_module VARCHAR(100)
    );
    """)
    op.execute("CREATE INDEX idx_raw_content_store_source_node_id ON raw_content_store(source_node_id);")

    op.execute("""
    CREATE TABLE content_items (
        id BIGSERIAL PRIMARY KEY,
        source_node_id INTEGER NOT NULL REFERENCES source_nodes(id) ON DELETE CASCADE,
        raw_content_id INTEGER NOT NULL REFERENCES raw_content_store(id) ON DELETE CASCADE,
        chunk_sequence_number INTEGER NOT NULL,
        text_content TEXT NOT NULL,
        text_content_redacted TEXT,
        chunking_strategy VARCHAR(100),
        metadata JSONB,
        status content_item_status NOT NULL DEFAULT 'RAW',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (source_node_id, chunk_sequence_number)
    );
    """)
    op.execute("CREATE INDEX idx_content_items_status ON content_items(status);")
    op.execute("CREATE INDEX idx_content_items_source_node_id ON content_items(source_node_id);")
    op.execute("CREATE INDEX idx_content_items_raw_content_id ON content_items(raw_content_id);")

    op.execute("""
    CREATE TABLE pii_annotations (
        id BIGSERIAL PRIMARY KEY,
        content_item_id BIGINT NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
        pii_type pii_type NOT NULL,
        start_offset INTEGER NOT NULL,
        end_offset INTEGER NOT NULL,
        detected_value TEXT NOT NULL,
        confidence_score FLOAT,
        detection_module VARCHAR(100),
        is_redacted BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    """)
    op.execute("CREATE INDEX idx_pii_annotations_content_item_id ON pii_annotations(content_item_id);")
    op.execute("CREATE INDEX idx_pii_annotations_pii_type ON pii_annotations(pii_type);")

    op.execute("""
    CREATE TABLE exported_golden_rows (
        id BIGSERIAL PRIMARY KEY,
        pipeline_run_id INTEGER NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
        content_item_id BIGINT NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
        export_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        exported_filename VARCHAR(1024),
        UNIQUE (pipeline_run_id, content_item_id, exported_filename)
    );
    """)
    op.execute("CREATE INDEX idx_exported_golden_rows_pipeline_run_id ON exported_golden_rows(pipeline_run_id);")
    op.execute("CREATE INDEX idx_exported_golden_rows_content_item_id ON exported_golden_rows(content_item_id);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in reverse order of creation, handling dependencies
    op.execute("DROP TABLE IF EXISTS exported_golden_rows CASCADE;")
    op.execute("DROP TABLE IF EXISTS pii_annotations CASCADE;")
    op.execute("DROP TABLE IF EXISTS content_items CASCADE;")
    op.execute("DROP TABLE IF EXISTS raw_content_store CASCADE;")
    op.execute("DROP TABLE IF EXISTS source_nodes CASCADE;")
    op.execute("DROP TABLE IF EXISTS pipeline_runs CASCADE;")
    op.execute("DROP TABLE IF EXISTS data_sources CASCADE;")

    # Drop enums in reverse order of creation (or if not dependent, any order)
    op.execute("DROP TYPE IF EXISTS data_source_type;")
    op.execute("DROP TYPE IF EXISTS pii_type;")
    op.execute("DROP TYPE IF EXISTS content_item_status;")
    op.execute("DROP TYPE IF EXISTS source_node_status;")
    op.execute("DROP TYPE IF EXISTS job_status;")
    # ### end Alembic commands ###
