"""Initial schema for Client-Role data model (manual)

Revision ID: d9a510162558
Revises:
Create Date: 2025-06-03 20:37:30.061739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# import sqlmodel # Not strictly needed for raw SQL execution but good practice if using SQLModel features


# revision identifiers, used by Alembic.
revision: str = 'd9a510162558'
down_revision: Union[str, None] = None # Corrected: This should be the first migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands from database_schema.sql ###

    # Enum for Role Status
    op.execute("""
    CREATE TYPE role_status_enum AS ENUM (
        'DRAFT',
        'PARSED',
        'VERIFIED',
        'FLAGGED',
        'ARCHIVED'
    );
    """)

    # Clients table
    op.execute("""
    CREATE TABLE clients (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        display_name TEXT NOT NULL,
        notes TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    """)
    op.execute("CREATE INDEX idx_clients_display_name ON clients(display_name);")

    # Source documents table
    op.execute("""
    CREATE TABLE source_documents (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
        file_name TEXT NOT NULL,
        file_type VARCHAR(50),
        content_hash VARCHAR(64),
        raw_text TEXT,
        uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        processing_status VARCHAR(50) DEFAULT 'PENDING',
        metadata JSONB
    );
    """)
    op.execute("CREATE INDEX idx_source_documents_client_id ON source_documents(client_id);")
    op.execute("CREATE INDEX idx_source_documents_content_hash ON source_documents(content_hash);")

    # Roles table
    op.execute("""
    CREATE TABLE roles (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
        company_name TEXT NOT NULL,
        title TEXT NOT NULL,
        start_date DATE,
        end_date DATE,
        output_text TEXT,
        input_text_compact TEXT,
        status role_status_enum DEFAULT 'PARSED',
        revision INTEGER DEFAULT 0,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    """)
    op.execute("CREATE INDEX idx_roles_client_id ON roles(client_id);")
    op.execute("CREATE INDEX idx_roles_company_name ON roles(company_name);")
    op.execute("CREATE INDEX idx_roles_title ON roles(title);")

    # Evidence snippets table
    op.execute("""
    CREATE TABLE evidence_snippets (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        source_document_id UUID NOT NULL REFERENCES source_documents(id) ON DELETE CASCADE,
        role_id UUID REFERENCES roles(id) ON DELETE SET NULL,
        snippet_text TEXT NOT NULL,
        file_name TEXT,
        page_number INTEGER,
        line_number_start INTEGER,
        line_number_end INTEGER,
        metadata JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    """)
    op.execute("CREATE INDEX idx_evidence_snippets_source_document_id ON evidence_snippets(source_document_id);")
    op.execute("CREATE INDEX idx_evidence_snippets_role_id ON evidence_snippets(role_id);")

    # Validation notes table
    op.execute("""
    CREATE TABLE validation_notes (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        role_id UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
        note_text TEXT NOT NULL,
        author VARCHAR(255),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    """)
    op.execute("CREATE INDEX idx_validation_notes_role_id ON validation_notes(role_id);")

    # Trigger for updated_at in roles table
    op.execute("""
    CREATE OR REPLACE FUNCTION trigger_set_timestamp()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER set_roles_updated_at
    BEFORE UPDATE ON roles
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_timestamp();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS set_roles_updated_at ON roles;")
    op.execute("DROP FUNCTION IF EXISTS trigger_set_timestamp();")

    op.execute("DROP TABLE IF EXISTS validation_notes CASCADE;")
    op.execute("DROP TABLE IF EXISTS evidence_snippets CASCADE;")
    op.execute("DROP TABLE IF EXISTS roles CASCADE;")
    op.execute("DROP TABLE IF EXISTS source_documents CASCADE;")
    op.execute("DROP TABLE IF EXISTS clients CASCADE;")

    op.execute("DROP TYPE IF EXISTS role_status_enum;")
    # ### end Alembic commands ###
